# 14 de febrero

Esto es un texto que no contiene código en Python

In [3]:
print("Que bonito dia!")

Que bonito dia!


## Pruebas de arange y range

In [8]:
import numpy as np

print("np.arange(10) ==>", np.arange(10))
print("np.arange(3, 10) ==>", np.arange(3, 10))
print("np.arange(1, 10, 2) ==>", np.arange(1, 10, 2))
print("np.arange(10, 0, -1) ==>", np.arange(10, 0, -1))
print("np.arange(10, 0, -2) ==>", np.arange(10, -1, -2))

np.arange(10) ==> [0 1 2 3 4 5 6 7 8 9]
np.arange(3, 10) ==> [3 4 5 6 7 8 9]
np.arange(1, 10, 2) ==> [1 3 5 7 9]
np.arange(10, 0, -1) ==> [10  9  8  7  6  5  4  3  2  1]
np.arange(10, 0, -2) ==> [10  8  6  4  2  0]


In [13]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [14]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

## Tipos de datos

In [19]:
5 + 3.0  # esto da un numero de punto flotante

8.0

In [20]:
int(5 + 3.0)  # esto lo convierte a entero

8

In [21]:
type(5)

int

In [22]:
type(3.0)

float

In [23]:
type([1,2,3,4,5])

list

In [24]:
type((1,2,3,4,5))

tuple

In [25]:
type({1,2,3,4,5})

set

In [26]:
type({"apple":"manzana", "pineapple":"piña"})

dict

In [27]:
class Chivito:
    pass

x = Chivito()
type(x)

__main__.Chivito

In [28]:
type(3+5j)

complex

In [29]:
type(np.arange(10))

numpy.ndarray

In [30]:
type(np.array([6,2,4,1,3]))

numpy.ndarray

In [31]:
x = np.arange(10)

type(x)

numpy.ndarray

In [32]:
type("Paty se fué")

str

In [34]:
import pandas as pd

type(pd.DataFrame())

pandas.core.frame.DataFrame

In [36]:
type(np.matrix([[1,2],[3,4]]))

numpy.matrixlib.defmatrix.matrix

In [37]:
print([1,2,3,4,5])

[1, 2, 3, 4, 5]


In [38]:
print([5,3,6,4,2,9])

[5, 3, 6, 4, 2, 9]


In [40]:
for x in [5,3,6,4,2,9]:
    print(x, x**2)

5 25
3 9
6 36
4 16
2 4
9 81


In [41]:
"*" * 5

'*****'

In [43]:
for x in [5,3,6,4,2,9]:
    print("*" * x)

*****
***
******
****
**
*********


In [44]:
np.arange(0, 1, .2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [48]:
# range(0,1,.2)  # esto es un error

In [51]:
for x in range(1, 11):
    print(x, x**2)

1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100


In [52]:
for x in range(1, 11):
    print("*" * x)

*
**
***
****
*****
******
*******
********
*********
**********


In [54]:
np.arange(1,11) * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [58]:
a = np.arange(1,101)

In [59]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [60]:
aa = a.reshape((10,10))

In [61]:
aa

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])